// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Control
{
    [flags]
    enum KeyModifiers
    {
        None = 0x0000,
        Alt = 0x0001,
        Ctrl = 0x0002,
        Shift = 0x0004,
        Windows = 0x0008
    };

    [default_interface]
    runtimeclass KeyChord
    {
        KeyChord();
        KeyChord(KeyModifiers modifiers, Int32 vkey, Int32 scanCode);
        KeyChord(Boolean ctrl, Boolean alt, Boolean shift, Boolean win, Int32 vkey, Int32 scanCode);

        KeyModifiers Modifiers;
        Int32 Vkey;
        Int32 ScanCode;
    }
}
